### ISSUE TITLE
Can't install the template

### ISSUE THREAD

**Issue by carcam** [anibalsanchez/XT-G5_tailwind#3]
After merging latest changes, the release file generated cannot be installed due to the error:

> JInstaller: :Install: File does not exist /app/www/tmp/install_5e83506f01c7e/library/prefixed_vendor
> Library %s: Could not copy files from the source.
> Package Install: There was an error installing an extension: library

I have been checking and the problem seems to be that  the manifest file for the library file is referencing a folder called _prefixed_vendor_ which is not present.

After executing `composer install` inside the library folder a new _vendor_ folder is added, but no _prefixed_vendor_ file.

**Comment by anibalsanchez** [comment]
Solved!
